# Generated by Django 5.2.7 on 2025-12-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='item',
        ),
    ]
